before_script:
  - module use /usr/share/modules/
  - module load gnu-openmpi/1.8.8

build-serial:
  script:
    - mkdir build-serial
    - pushd build-serial
    - cmake ../ -DWITH_MPI=OFF -DWITH_OPENMP=OFF
    - make -j10 
    - popd

build-mpi-pure:
  script:
    - mkdir build-mpi-pure
    - pushd build-mpi-pure
    - cmake ../ -DWITH_MPI=ON -DWITH_OPENMP=OFF
    - make -j10 
    - popd

build-old-hpc:
  script:
    - cp -r source source-mpi
    - pushd source-mpi
    - ln -s ../build/Makefile_MPI Makefile
    - make hpc   
