variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - module use /opt/modules/

stages:
  - build
  - test

build-serial:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-serial.sh
    - sh utils/build-serial-evb.sh
  only:
    - merge_requests

build-openmp-pure:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-openmp-pure.sh
  only:
    - merge_requests


build-mpi-pure:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-pure.sh
    - sh utils/build-mpi-evb.sh
  only:
    - merge_requests

build-mpi-plumed:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-plumed.sh
  only:
    - merge_requests

build-mpi-plumed-internal:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-plumed-internal.sh
  only:
    - merge_requests

build-mpi-kim:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-kim.sh
  only:
    - merge_requests

build-mpi-kim-internal:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-kim-internal.sh
  only:
    - merge_requests

build-mpi-all:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-all.sh
  only:
    - merge_requests

#build-gcc-dftbp:
#  stage: build
#  tags:
#    - gcc
#  script:
#    - sh utils/build-mpi-gnu-dftbp.sh

build-intel:
  stage: build
  tags:
    - intel
  script:
    - sh utils/build-intel.sh
    - sh utils/build-intel-evb.sh
build-ifx:
  stage: build
  tags:
    - intel
  script:
    - sh utils/build-ifx.sh
  only:
    - merge_requests

      #build-intel-dftbp:
      #  stage: build
      #  tags:
      #    - intel
      #  script:
      #    - sh utils/build-intel-dftbp.sh

#build-manual:
#  stage: manual
#  script:
#    - cd manual
#    - ./makedoc MANUAL_USR

build-win32-serial:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-win32-serial.sh
  only:
    - merge_requests

build-win64-serial:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-win64-serial.sh
  only:
    - merge_requests

#build-win32-msmpi:
#  stage: build
#  tags:
#    - gcc
#  script:
#    - sh utils/build-win32-msmpi.sh
#
#build-win64-msmpi:
#  stage: build
#  tags:
#    - gcc
#  script:
#    - sh utils/build-win64-msmpi.sh

testing-mpi-gcc:
  stage: test
  tags:
    - gcc
  script:
    - sh utils/mpi-testing.sh
  only:
    - merge_requests

testing-mpi-gcc-paranoid:
  stage: test
  tags:
    - gcc
  script:
    - sh utils/mpi-testing-paranoid.sh
  only:
    - merge_requests

testing-mpi-intel:
  stage: test
  tags:
    - intel
  script:
    - sh utils/intel-testing.sh
  only:
    - merge_requests

testing-mpi-ifx:
  stage: test
  tags:
    - intel
  script:
    - sh utils/ifx-testing.sh
  only:
    - merge_requests

testing-mpi-intel-paranoid:
  stage: test
  tags:
    - intel
  script:
    - sh utils/intel-testing-paranoid.sh
  except:
    - devel
  only:
    - merge_requests
