before_script:
  - module use /opt/modules/
  - module load openmpi/gcc/1.10.1
  - module load netcdf/gcc/4.4.0
  - module load plumed/gcc/2.2.1
  - module load kim/gcc/1.7.2

stages:
  - build
  - test

build-serial:
  stage: build
  script:
    - mkdir build-serial
    - pushd build-serial
    - cmake ../ -DWITH_MPI=OFF 
    - make -j10 
    - popd

build-mpi-pure:
  stage: build
  script:
    - mkdir build-mpi-pure
    - pushd build-mpi-pure
    - cmake ../ 
    - make -j10 
    - popd

build-mpi-netcdf:
  stage: build
  script:
    - mkdir build-mpi-netcdf
    - pushd build-mpi-netcdf
    - cmake ../ -DWITH_NETCDF=ON 
    - make -j10 
    - popd

build-mpi-plumed:
  stage: build
  script:
    - mkdir build-mpi-plumed
    - pushd build-mpi-plumed
    - cmake ../ -DWITH_PLUMED=ON 
    - make -j10 
    - popd

build-mpi-kim:
  stage: build
  script:
    - mkdir build-mpi-kim
    - pushd build-mpi-kim
    - cmake ../ -DWITH_KIM=ON 
    - make -j10 
    - popd

build-mpi-all:
  stage: build
  script:
    - mkdir build-mpi-all
    - pushd build-mpi-all
    - cmake ../ -DWITH_KIM=ON -DWITH_PLUMED=ON -DWITH_NETCDF=ON 
    - make -j10 
    - popd
build-intel: 
  stage: build
  script:
    - mkdir build-mpi-intel
    - pushd build-mpi-intel
    - sh ../utils/build-intel.sh 
    - popd

build-old-hpc:
  stage: build
  script:
    - cp -r source source-mpi
    - pushd source-mpi
    - ln -s ../build/Makefile_MPI Makefile
    - make hpc 
  only:
    - master

testing-mpi:
  stage: test
  script:
    - mkdir build-mpi-plumed
    - pushd build-mpi-plumed
    - FFLAGS="-O3 -mtune=native" cmake ../ -DBUILD_TESTING=ON -DWITH_PLUMED=ON -DBUILDER="Gitlab Slave"
    - make -j10 
    - make test  
    - popd 
  only:
    - master
