variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - source utils/modules.sh

stages:
  - manual
  - pages
  - build
  - test

build-serial:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-serial.sh
    - sh utils/build-serial-evb.sh
  only:
    - devel
    - merge_requests

build-openmp-pure:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-openmp-pure.sh
  only:
    - merge_requests


build-mpi-pure:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-pure.sh
    - sh utils/build-mpi-evb.sh
  only:
    - merge_requests

build-mpi-plumed:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-plumed.sh
  only:
    - merge_requests

build-mpi-plumed-internal:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-plumed-internal.sh
  only:
    - merge_requests

build-mpi-kim:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-kim.sh
  only:
    - merge_requests

build-mpi-kim-internal:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-kim-internal.sh
  only:
    - merge_requests

build-mpi-all:
  stage: build
  tags:
    - gcc
  script:
    - sh utils/build-mpi-all.sh
  only:
    - merge_requests


build-intel:
  stage: build
  tags:
    - intel
  script:
    - sh utils/build-intel.sh
    - sh utils/build-intel-evb.sh
  only:
    - merge_requests

build-ifx:
  stage: build
  tags:
    - intel
  script:
    - sh utils/build-ifx.sh
  only:
    - merge_requests

build-win32-serial:
  stage: build
  tags:
    - win
  script:
    - sh utils/build-win32-serial.sh
  only:
    - merge_requests

build-win64-serial:
  stage: build
  tags:
    - win
  script:
    - sh utils/build-win64-serial.sh
  only:
    - merge_requests

testing-mpi-gcc:
  stage: test
  tags:
    - gcc
  script:
    - sh utils/mpi-testing.sh
  only:
    - merge_requests

testing-mpi-gcc-paranoid:
  stage: test
  tags:
    - gcc
  script:
    - sh utils/mpi-testing-paranoid.sh
  only:
    - merge_requests

testing-mpi-intel:
  stage: test
  tags:
    - intel
  script:
    - sh utils/intel-testing.sh
  only:
    - merge_requests

testing-mpi-ifx:
  stage: test
  tags:
    - intel
  script:
    - sh utils/ifx-testing.sh
  only:
    - merge_requests

testing-mpi-intel-paranoid:
  stage: test
  tags:
    - intel
  script:
    - sh utils/intel-testing-paranoid.sh
  except:
    - devel
  only:
    - merge_requests

build-html:
  image: alpine
  stage: manual
  script:
    - apk --no-cache add py3-pip python3-dev
    - pip install sphinx groundwork-sphinx-theme
    - apk --no-cache add make
    - cd documentation
    - make html
  only:
    - devel
    - merge_requests

pages:
  image: alpine
  stage: pages
  script:
  - apk --no-cache add py3-pip python3-dev
  - pip install sphinx groundwork-sphinx-theme
  - apk --no-cache add make
  - cd documentation
  - make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
    - devel
