before_script:
  - module use /opt/modules/

stages:
  - build
  - test

build-serial:
  stage: build
  script:
    - sh utils/build-serial.sh

build-openmp-pure:
  stage: build
  script:
    - sh utils/build-openmp-pure.sh

build-mpi-pure:
  stage: build
  script:
    - sh utils/build-mpi-pure.sh

build-mpi-netcdf:
  stage: build
  script:
    - sh utils/build-mpi-netcdf.sh

build-mpi-plumed:
  stage: build
  script:
    - sh utils/build-mpi-plumed.sh

build-mpi-kim:
  stage: build
  script:
    - sh utils/build-mpi-kim.sh

build-mpi-all:
  stage: build
  script:
    - sh utils/build-mpi-all.sh

build-intel:
  stage: build
  script:
    - sh utils/build-intel.sh

build-old-hpc:
  stage: build
  script:
    - sh utils/build-old.sh
  only:
    - master

build-win32-serial:
  stage: build
  script:
    - sh utils/build-win32-serial.sh

build-win64-serial:
  stage: build
  script:
    - sh utils/build-win64-serial.sh

build-win32-msmpi:
  stage: build
  script:
    - sh utils/build-win32-msmpi.sh

build-win64-msmpi:
  stage: build
  script:
    - sh utils/build-win64-msmpi.sh

testing-mpi-gcc:
  stage: test
  script:
    - sh utils/mpi-testing.sh

testing-mpi-gcc-paranoid:
  stage: test
  script:
    - sh utils/mpi-testing-paranoid.sh

testing-mpi-intel:
  stage: test
  script:
    - sh utils/intel-testing.sh
