before_script:
  - module use /usr/share/modules/
  - module av
  - module load gnu-openmpi/1.8.8

build-hpc:
  script:
    - pushd source
    - ln -s ../build/Makefile_MPI Makefile
    - make hpc   
