#!/bin/sh
# Clean old compilation
#
mv $1.tex .$1.tex
rm -f $1.*
mv .$1.tex $1.tex

# First round
#
latex $1.tex

# Process indices
#
bibtex $1.aux
makeindex $1.idx

# Three more rounds
#
latex $1.tex
latex $1.tex
latex $1.tex

# Convert to PDF
#
dvipdfm -o $1.pdf $1.dvi

# Clean compilation
#
mv $1.tex .$1.tex
mv $1.pdf .$1.pdf
rm -f $1.*
mv .$1.tex $1.tex
mv .$1.pdf $1.pdf
