#!/usr/bin/env python3

"""
Run a DL_POLY test case using dlpoly-py

Each test case is defined by an input data archive and
a reference data archive stored on Github 
https://github.com/ccp5UK/dl-poly-data.

The input data archive typically contains a CONTROL, 
CONFIG, and FIELD file, but may also contain any other
input files. A custom test runner can be used by defining
a run_test.py in the input data archive, alongside any
custom reference datain the reference archive.

By default the test runs utils/test-statis.py which
checks the values of a reference STATIS against the one
generated by the given DL_POLY run.

The input data must define a test.yml file which 
may set a test tolerance.

	# %YAML 1.2
	test:
	  name: "178"
	  title: ""
	  type: "regression"              
	  tolerances: 
	      default: 0.0001

A run-test.py file given in the input archive must define
an actual(**kwargs) function and an expected(**kwargs) 
function to obtain the observed data on this test run 
and the expected data.

Test run data (including extracted inputs) will be copied
to a folder CMAKE_BINARY_DIR/Testing/TestsOut/TESTXXX/ 
where the test will be run.        
"""

from ruamel.yaml import YAML
import numpy as np
import sys
from pathlib import Path
import argparse
import tarfile

parser = argparse.ArgumentParser(description='Test DL_POLY')

parser.add_argument('--exe', type=Path, default=None, help='location of DLPOLY.Z executable')
parser.add_argument('--np', type=int, default=1, help='number of processes')
parser.add_argument('--mpi', type=str, default='mpirun -n', help='mpi executable')
parser.add_argument('--verbose', action='store_true', help='verbose output')
parser.add_argument('--save', action='store_true', help='save results')
parser.add_argument('--name', type=str, default="", help="name of test to run, e.g. TESTXXX")
parser.add_argument('--binary_dir', type=Path, default="", help="absolute path to repository binary dir")
parser.add_argument('--src_dir', type=Path, default="", help="absolute path to the dlpoly source tree")
args = parser.parse_args()

verbose = args.verbose

root_dir = args.src_dir.absolute()
test_dir = args.binary_dir.absolute()/"Testing"
ref_dir = root_dir/"data/reference"
test_out_dir = test_dir/"TestsOut"
test_work_dir = test_out_dir/args.name

if not test_out_dir.exists():
    test_out_dir.mkdir()

if not test_work_dir.exists():
    test_work_dir.mkdir()

input_tar = test_dir/f"{args.name}/{args.name}.tar.xz"
reference_tar = ref_dir/f"{args.name}.tar.xz"

if not tarfile.is_tarfile(input_tar):
    raise Exception(f"Input data at {input_tar} is not a tarfile")

if not tarfile.is_tarfile(reference_tar):
    raise Exception(f"Reference data at {reference_tar} is not a tarfile")

tarfile.open(input_tar).extractall(test_out_dir)
tarfile.open(reference_tar).extractall(ref_dir)

yaml_parser = YAML()

test_yaml = ref_dir/args.name/"test.yml"
if not test_yaml.exists():
    raise Exception(f"No test.yml at {test_yaml}")
    
with test_yaml.open('rb') as in_file:
    test = yaml_parser.load(in_file)['test']

if verbose:
    print("Test case {}".format(test["title"]))

test_result_string = """\
Passed: False
Results: {}
"""

results = yaml_parser.load(test_result_string)

if (test_work_dir/"runtest.py").is_file():
    sys.path.append(str(test_work_dir))
    testcase = __import__('runtest')
else:
    testcase = __import__("test-statis")

actual = testcase.actual(workdir=test_work_dir, exe=args.exe, numProcs=args.np, mpi=args.mpi)
expected = testcase.expected(reference_dir=ref_dir/args.name)

passes = []

test_type = test.get("type", "absolute")

if test_type == "absolute":
    passes = [actual == expected]
    results["Results"] = {"Passed": str(actual == expected)}
else:
    default_tolerance = 1e-6
    tolerances = {}
    if "tolerances" in test and isinstance(test["tolerances"],dict):
        default_tolerance = test["tolerances"].get("default", default_tolerance)

    if isinstance(actual, dict):
        for val in actual:
            tolerance = tolerances.get(val, default_tolerance)
            e = np.mean((actual[val]-expected[val])**2)
            results["Results"][val] = {"Mean square error": str(e),
                                       "Tolerance": str(tolerance),
                                       "Passed": str(e < tolerance)}
            passes.append(e < tolerance)
    else:
        tolerance = default_tolerance
        e = np.mean((actual-expected)**2)
        results["Results"] = {"Mean square error": str(e),
                              "Tolerance": str(tolerance),
                              "Passed": str(e < tolerance)}
        passes.append(e < tolerance)

passed = all(passes)

results['Passed'] = str(passed)

if passed:
    print("Status: PASSED\n")
else:
    print("Status: FAILED")

if args.save:
    yaml_parser.dump(results, test_dir)
else:
    yaml_parser.dump(results, sys.stdout)
