from dlpoly.control import NewControl as Control

from ruamel.yaml import YAML
from tempfile import NamedTemporaryFile as tmp
from pathlib import Path
from subprocess import run
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('dlp', type=Path, help="DLPOLY.Z path")
parser.add_argument('--mpi', type=str, help="MPI command", default="")
args = parser.parse_args()

yaml = YAML()

CONFIG = """CONFIG generated by ASE                                                 
         0         0 4
Ar               1
        0.0000000000        0.0000000000        0.0000000000
Ar               2
        2.6300000000        2.6300000000        0.0000000000
Ar               3
        2.6300000000        0.0000000000        2.6300000000
Ar               4
        0.0000000000        2.6300000000        2.6300000000
"""

FIELD = """lj
units eV
molecular types 1
1 argon atoms
nummols       4
atoms 1
Ar             39.95      0.0     1     0    1
finish
vdw        1
Ar      Ar      lj  0.01032   3.40
close
"""

CONTROL = """title DL_POLY Test of command line options

cutoff                        2      ang
ensemble                      nve
ensemble_method               hoover
ensemble_thermostat_coupling  1      ps
ensemble_barostat_coupling    1      ps

time_run                      0      steps
timestep                      0.001  ps

pressure_hydrostatic          1      bar
temperature                   60     K

stats_frequency               10     steps
time_job                      1000.0 s
time_close                    100.0  s
"""

overrides = {
        'ensemble_method': 'berendsen',
        'temperature': "80 K",
        'pressure_hydrostatic': "1 kbar",
        'timestep': "0.1 fs"
    }


config_file, field_file, control_file = [tmp(mode=('w'), delete=False) for i in range(3)]
files = [config_file, field_file, control_file]

for (file, data) in zip(files, [CONFIG, FIELD, CONTROL]):
    file.file.write(data)
    file.file.flush()

control = Control(control_file.name)

control['io_file_field'] = field_file.name
control['io_file_config'] = config_file.name
control.write(control_file.name)

if args.mpi != "":
    cmd = args.mpi.split()
    cmd.extend([str(args.dlp), "-c", control_file.name])
else:
    cmd = [str(args.dlp), "-c", control_file.name]

for (override, value) in overrides.items():
    cmd.extend([f"--{override}", value])

print(cmd)
run(cmd)

passed = True

with open("OUTPUT") as output:
    parsed_output = yaml.load(output.read())
    overrides_set = parsed_output['Command line CONTROL overrides']

    if overrides_set != overrides:
        print("Status: FAILED, control overrides incorrect")
        print(f"Expected {overrides}")
        print(f"Actual {overrides_set}")
        passed = False

    temperature = parsed_output['System parameters']['Simulation temperature (K)']
    pressure = parsed_output['System parameters']['Simulation pressure (GPa)']
    timestep = parsed_output['System parameters']['Fixed simulation timestep (ps)']
    if  temperature != 80.0:
        print("Status: FAILED, simulation temperature not correct")
        print("Expected: 80")
        print("Actual: ", temperature)
        passed = False
    if pressure != 0.1:
        print("Status: FAILED, simulation pressure not correct")
        print("Expected: 0.1")
        print("Actual", pressure)
        passed = False
    if timestep != 1e-4:
        print("Status: FAILED, simulation timestep not correct")
        print("Expected: 1e-4")
        print("Actual: ", timestep)
        passed = False

if passed:
    print("Status: PASSED")
else:
    print("Status: FAILED")

for file in files:
    file.close()
