option(WITH_MPI "build a MPI version" ON)
option(WITH_OPENMP "build an OpenMP version" OFF)
option(WITH_NETCDF "build using netcdf support version" OFF)
option(WITH_EXTRATIME "activate extra timing information" ON)
option(WITH_KIM "Build with KIM support" OFF)
option(INTERNAL_KIM "Build with Internal KIM rather than external" ON)
option(WITH_PLUMED "Build with PLUMED support" OFF)
option(INTERNAL_PLUMED "Build with Internal KIM rather than external" ON)
option(BUILD_TESTING "Build with Testing support" OFF)
option(WITH_COVERAGE "Build with instrumentation for code coverage" OFF)
option(DOCS_DOXYGEN "Doxygen Documentation" OFF)
option(WITH_FORCHECK "Build with forcheck for code" OFF)
option(WITH_EVB "Build with EVB for code" OFF)
option(DOCS_FORD "Ford Documentation" OFF)
option(BUILD_SHARED_LIBS "Build with shared libraries" OFF)
option(WITH_ASSERT "Build with asserts" OFF)

set(MPI_NPROCS 8 CACHE STRING "number of MPI processes to be used for code coverage and tests")
cmake_host_system_information(RESULT AH QUERY FQDN)
set(HOST "${AH}" CACHE STRING "name of the hostname we build on.")
set(BUILDER "" CACHE STRING "name of the person who built the binary.")
