SET(CMAKE_SYSTEM_NAME Windows)

SET(CMAKE_C_COMPILER    x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER  x86_64-w64-mingw32-g++)
SET(CMAKE_Fortran_COMPILER x86_64-w64-mingw32-gfortran)
SET(CMAKE_RC_COMPILER   x86_64-w64-mingw32-windres)
SET(CMAKE_LINKER    x86_64-w64-mingw32-ar)

SET(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32/sys-root/mingw)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

#SET(QT_QMAKE_EXECUTABLE /usr/i686-w64-mingw32/bin/qt5/qmake CACHE INTERNAL "" FORCE)
#SET(QT_MOC_EXECUTABLE /usr/i686-w64-mingw32/bin/qt5/moc CACHE INTERNAL "" FORCE)
#SET(QT_RCC_EXECUTABLE /usr/i686-w64-mingw32/bin/qt5/rcc CACHE INTERNAL "" FORCE)
#SET(QT_UIC_EXECUTABLE /usr/i686-w64-mingw32/bin/qt5/uic CACHE INTERNAL "" FORCE)
